# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

require 'json'

vms_config = JSON.parse(ENV['vms_config'])

# Imprimir vms_config en la consola
#puts "vms_config in vagrant:"
#puts JSON.pretty_generate(vms_config)

Vagrant.configure("2") do |config|

  vms_config['vms'].each do |vm|

    config.vm.define vm['hostname'] do |subconfig|
      subconfig.vm.box = vm['box_image']
      subconfig.vm.hostname = vm['hostname']
      subconfig.vm.network :private_network, ip: vm['ip']

      # El nombre en virtual box
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "#{vm['hostname']}_#{vm['ip']}"
        vb.memory = vm['memory']
        vb.cpus = vm['cpus']
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end

      configure_vm_script(subconfig, vm['script'])
      
      if !vm['upfirsttime']
        subconfig.vm.synced_folder vm['shared_folder_host'], vm['shared_folder_vm'], create: true , owner: vm['username'], group: vm['username']
      end

    end    
  end
end


def configure_vm_script(config, script)

  script = script.downcase
  unless script.to_s.strip.empty?
    config.vm.provision "shell", inline: <<-SHELL
      echo "Copiando y ejecutando el script...#{script}"
      mkdir -p scripts_to_provision
      cp /vagrant/scripts_to_provision/#{script} /home/vagrant/scripts_to_provision/
      cp /vagrant/scripts_to_provision/install.sh /home/vagrant/scripts_to_provision/
      ls /home/vagrant/scripts_to_provision
      chmod +x /home/vagrant/scripts_to_provision/#{script}
      chmod +x /home/vagrant/scripts_to_provision/install.sh
      /home/vagrant/scripts_to_provision/#{script}
    SHELL
  else
    config.vm.provision "shell", inline: <<-SHELL
      echo "Copiando y ejecutando el script..."
      mkdir -p scripts_to_provision
      cp /vagrant/scripts_to_provision/install.sh /home/vagrant/scripts_to_provision
      chmod +x /home/vagrant/scripts_to_provision/install.sh
      /home/vagrant/scripts_to_provision/install.sh
    SHELL
  end

end